# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmsession',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='film_sessions', to='root.Cinema'),
        ),
    ]
