# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20171028_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='root.Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='cinemaplaces',
            unique_together=set([('row', 'position')]),
        ),
    ]
