# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20171028_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaplaces',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinemaplaces',
            name='film_Session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='root.FilmSession'),
        ),
        migrations.AlterField(
            model_name='film',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 10, 30)),
        ),
    ]
