# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20171030_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='root.Genre'),
        ),
    ]
