# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20171030_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaplaces',
            name='position',
            field=models.IntegerField(validators=[rest_framework.compat.MaxValueValidator(100), rest_framework.compat.MinValueValidator(1)]),
        ),
    ]
