# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20171030_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaplaces',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
