# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20171030_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsession',
            name='price',
        ),
        migrations.AddField(
            model_name='cinemaplaces',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
