# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0009_auto_20171030_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSessionPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[rest_framework.compat.MinValueValidator(0)])),
                ('film_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='root.FilmSession')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cinemaplaces',
            name='film_Session',
        ),
        migrations.RemoveField(
            model_name='cinemaplaces',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cinemaplaces',
            name='price',
        ),
        migrations.AddField(
            model_name='cinemaplaces',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='root.Cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmsessionplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.CinemaPlaces'),
        ),
    ]
