# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20171030_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaplaces',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='root.Cinema'),
        ),
    ]
