# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0011_auto_20171030_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSessionPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[rest_framework.compat.MinValueValidator(0)])),
                ('film_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='root.FilmSession')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.CinemaPlaces')),
            ],
        ),
        migrations.RemoveField(
            model_name='filmsessionplace',
            name='film_session',
        ),
        migrations.RemoveField(
            model_name='filmsessionplace',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='filmsessionplace',
            name='place',
        ),
        migrations.DeleteModel(
            name='FilmSessionPlace',
        ),
    ]
