# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_auto_20171030_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cinemaplace',
            unique_together=set([('cinema', 'row', 'position')]),
        ),
    ]
