# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20171030_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsessionplace',
            name='price',
            field=models.FloatField(default=0.0, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
    ]
